old_sound_rabbit_mq:
    connections:
        default:
            #url: '%env(RABBITMQ_URL)%'
            host:     '%env(RABBITMQ_HOST)%'
            port:     %env(RABBITMQ_PORT)%
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '%env(RABBITMQ_VHOST)%'

            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0

        ssl_connection:
            host:     '%env(RABBITMQ_HOST)%'
            port:     5671
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '%env(RABBITMQ_VHOST)%'

            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0

            ssl_context:
                cacert:   '/var/www/html/rabbitmqExperiments/config/ssl/testca/cacert.pem'
                local_cert:   '/var/www/html/rabbitmqExperiments/config/ssl/client/cert.pem'
                local_pk:     '/var/www/html/rabbitmqExperiments/config/ssl/client/key.pem'
                verify_peer: false
                verify_peer_name: false
                allow_self_signed: true
                ciphers: 'TLSv1.2'

    producers:
        # use 'old_sound_rabbit_mq.my_task_producer' service to send data.
        my_task:
            connection:       default
            exchange_options: { name: 'myExchange', type: direct }

    consumers:
        my_task:
            connection:       default
            exchange_options: { name: 'myExchange', type: direct }
            queue_options:    { name: 'myQueue'}
            callback:         App\Consumer\TestConsumer
