old_sound_rabbit_mq:
    connections:
        default:
            #url: '%env(RABBITMQ_URL)%'
            host:     '%env(RABBITMQ_HOST)%'
            port:     %env(RABBITMQ_PORT)%
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '%env(RABBITMQ_VHOST)%'

            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            #use_socket: true # default false

    producers:
        # use 'old_sound_rabbit_mq.my_task_producer' service to send data.
        my_task:
            connection:       default
            exchange_options: { name: 'test', type: direct }

    consumers:
        my_task:
            connection:       default
            exchange_options: { name: 'test', type: direct }
            queue_options:    { name: 'test'}
            callback:         App\Consumer\TestConsumer
